intro_message = (
    "Welcome to Anya Shop Bot 0.1!\n"
    "\n"
    "***Detailed usage and installation instructions are in the README.md file.***\n"
    "\n"
    "Make sure Tesseract is installed and the path is correctly set in config.ini file.\n"
    "Ensure the game screen is set to 1280x720 in windowed mode, as specified in (README.md).\n"
    "Adjust the parameter values for items in config.ini according to your preferences.\n"
    "\n"
    "Press F1 to start the bot.\n"
    "Press F2 to stop the bot.\n"
    "Press F4 to terminate the bot and close this window.\n"
    "\n"
    "Proudly created by: johnovelli\n"
    "If you found this project useful, please consider giving it a star on GitHub. Thank you!\n"
    "\n"
    "\n"
    "***Logs of attributes with the required minimum value are saved in the 'logs' folder.\n"
    "Additionally, every log entry will also be displayed in the console window***\n"
)